Fix check for overlayfs when using tukit open with --discard
It used the full path to the parent snapshot's /etc for fstab lookup,
which did not work:

2025-04-16 14:25:57 Discarding snapshot 2.
ERROR: File system /.snapshots/1/snapshot/etc not found in fstab.

Look for /etc in the parent snapshot's /etc/fstab.